# Generated by Django 2.2 on 2019-05-26 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acora', '0016_auto_20190515_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='puntuacionTres',
            field=models.CharField(default='na', max_length=500),
        ),
    ]
